services:
  - type: web
    name: webcrawlai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: THORDATA_USERNAME
        sync: false
      - key: THORDATA_PASSWORD
        sync: false
      - key: THORDATA_PROXY_SERVER
        sync: false
      - key: GEMINI_API_KEY
        sync: false
